- KAFKA Basic
  - Section 1 : KAFKA 소개
  - Section 2 : KAFKA 이론
  - Section 3 : KAFKA 시작하기
  - Section 4 : KAFKA CLI
  - Section 5 : KAFKA Java Programming
  - Section 6 : KAFKA simple wikimedia Project and advanced Producer configuration
  - Section 7 : OpenSearch Consumer and advanced Consumer configurations
  - Section 8 : KAFKA 확장 API & 실제 사례
  - Section 9 : KAFKA 기업 가이드
  - Section 10 : 고급 KAFKA 토픽 구성